#!/bin/bash

make clean;
make

echo ""
echo "---------------------------- Resultat Attendu:"
echo ""
if [[ $# -eq 3 ]]
then
	arm-none-eabi-readelf "$1" "$2" "$3"
else
	arm-none-eabi-readelf "$1" "$2"
fi

echo ""
echo "---------------------------- Resultat Obtenu:"
echo ""
if [[ $# -eq 3 ]]
then
	./my_readelf "$1" "$2" "$3"
else
	./my_readelf "$1" "$2" "$3"
fi

