#!/bin/bash

if [[ $# -lt 1 ]]
then
	echo "Il faut un fichier ELF en argument !"
else
    ./my_readelf "$1" -R xxxxxxxxxxxxxxxxxx.out
    echo ">>>>> avant relocation : "
    ./my_readelf "$1" -x .data
    echo ">>>>> après relocation : "
    ./my_readelf xxxxxxxxxxxxxxxxxx.out -x .data
    echo ">>>>> avant relocation : "
    ./my_readelf "$1" -x .text
    echo ">>>>> après relocation : "
    ./my_readelf xxxxxxxxxxxxxxxxxx.out -x .text
fi
